POST https://localhost:7181/api/Manager/ChangeVacationStatus
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiOGJkZDIwYy05MjgyLTRjYjMtOGE0Yi05ZmM1OTQ4MGVlMzciLCJuYW1lIjoiT21hciIsImZhbWlseV9uYW1lIjoiU29saW1hbiIsImp0aSI6ImJmN2JkMjY2LWU0NjMtNGY3Yy1hZDhkLWVlMTI4ZTc1MTRkOCIsImV4cCI6MTcyNjEyODQ5OCwiaXNzIjoiUG9ydGFsIiwiYXVkIjoiUG9ydGFsIn0.SDyWXk8B-m4olmcsGYpB_krB4SV1wlND_gHmXDlT5VQ


{
  "vacationId": "3f9fdb1f-1f85-401e-a09e-37ece682eccd",
  "managerId": "27160222-9EC9-4D21-A0B9-3CB98310B7B9",
  "newStatus": "Approved"
}