@host=https://localhost:7181

POST {{host}}/api/Departments/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkZDdiZDdhMy0yZWE1LTRkZWYtOWMwNS1mZmIwYzdlZGJiYjUiLCJuYW1lIjoiU2F5ZWQiLCJmYW1pbHlfbmFtZSI6IlNvbGltYW4iLCJqdGkiOiIxYWZiNTU3Ni04NzRjLTQ4NzQtODRiMi0yMDQzODJmNDc2NzQiLCJleHAiOjE3MjUyNzM3MjksImlzcyI6IlBvcnRhbCIsImF1ZCI6IlBvcnRhbCJ9.DLwSadG6QcyLfrX1PE9XuQqbHsMKc90MwjVoUeUJYFQ

{

    "adminId": "AAA461B1-4FB3-411D-BDF2-646D9BA9B9D1",
    "departmentName": "StudentsAffairs",
    "managerId": "DD7BD7A3-2EA5-4DEF-9C05-FFB0C7EDBBB5"

}