@host=https://localhost:7181

POST {{host}}/api/Departments/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxNDM3OGQzZi0xYTBhLTRhNTAtYjM1OS0yYzc2NDgyZjAyMTUiLCJuYW1lIjoiTW91c3RhZmEiLCJmYW1pbHlfbmFtZSI6IlNvbGltYW4iLCJqdGkiOiIzNDFkZDcyYi1mM2Q1LTQzYTEtOTc1ZS04YThlMmI5YjcxMjkiLCJleHAiOjE3MjUxMzMzODMsImlzcyI6IlBvcnRhbCIsImF1ZCI6IlBvcnRhbCJ9.EkAa4EBrwWdkLhyvZJ1scWDEa2b0iQO2kwbKaATdNdE

{

    "adminId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
    "departmentName": "IT",
    "managerId": null

}