GET https://localhost:7181/Users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJQb3J0YWwuRG9tYWluLlVzZXIuVmFsdWVPYmplY3RzLlVzZXJJZCIsIm5hbWUiOiJPZGF5IiwiZmFtaWx5X25hbWUiOiJTb2xpbWFuIiwianRpIjoiODBkMDYwMTQtZmZlMi00NTMxLTliOWMtMzE1ZmI1MzQ0YjVlIiwiZXhwIjoxNzIzMzExMjgwLCJpc3MiOiJQb3J0YWwiLCJhdWQiOiJQb3J0YWwifQ.53zRuo9tSGFglHaRdqHnQvOGTdaKIzeIC2vCxOrtwqQ
