GET https://localhost:7181/Users/getAllUsers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxZDMyZTFhZS0wMTZiLTQxZDAtYmEwYy1lNjc4M2FhZTdmZGYiLCJuYW1lIjoiQWhtZWQiLCJmYW1pbHlfbmFtZSI6IlNvbGltYW4iLCJqdGkiOiI3OTc1OTNjMy1jNjIzLTQzN2EtODJmNi01Zjc1OGQ2YTljMWIiLCJleHAiOjE3MjYyNjA2ODUsImlzcyI6IlBvcnRhbCIsImF1ZCI6IlBvcnRhbCJ9.uTWEPeTa-zzqBN5DF0_IwzEHfN7gwks-EN_nF7VTkMs
Content-Type: application/json

{
  "adminId" : "ca7b76e7-80e4-4b3f-a5d1-268f83ba874e"
}