GET https://localhost:7181/Users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJQb3J0YWwuRG9tYWluLlVzZXIuVmFsdWVPYmplY3RzLlVzZXJJZCIsIm5hbWUiOiJNb3VzdGFmYSIsImZhbWlseV9uYW1lIjoiU29saW1hbiIsImp0aSI6ImIxM2ZjYTI3LTBmNWEtNDI4MS04MDI0LTExM2RhNjZmMzJhNiIsImV4cCI6MTcyMjQxNjA5OSwiaXNzIjoiUG9ydGFsIiwiYXVkIjoiUG9ydGFsIn0.RmsWHTTS57fCH8CgYmKYhS5QZ4eHQiZs3-OK0iiECRo
# eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJQb3J0YWwuRG9tYWluLlVzZXIuVmFsdWVPYmplY3RzLlVzZXJJZCIsIm5hbWUiOiJNb3VzdGFmYSIsImZhbWlseV9uYW1lIjoiU29saW1hbiIsImp0aSI6IjZiZGJlNWZhLTI5ODItNGVlOC1iOTEzLWU3YzMyYTI2MDk3MSIsImV4cCI6MTcyMjM3NjAyOCwiaXNzIjoiUG9ydGFsIiwiYXVkIjoiUG9ydGFsIn0.BmQBNFCo4Rp8Wp97ltbtaJjtz_hIOvDmdhCfRkP475M
#eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJQb3J0YWwuRG9tYWluLlVzZXIuVmFsdWVPYmplY3RzLlVzZXJJZCIsIm5hbWUiOiJNb3VzdGFmYSIsImZhbWlseV9uYW1lIjoiU29saW1hbiIsImp0aSI6IjdjZjQ4YTRjLTA3ZTUtNGZlMi1hZWI3LTYxMjEwNmRmMTZjYyIsImV4cCI6MTcyMjMyNjEyMCwiaXNzIjoiUG9ydGFsIiwiYXVkIjoiUG9ydGFsIn0.7BdSD31YWpSWG-pau8q81B7IH7hWCGwBSElduzXPPG0
# eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJQb3J0YWwuRG9tYWluLlVzZXIuVmFsdWVPYmplY3RzLlVzZXJJZCIsIm5hbWUiOiJzdHJpbmciLCJmYW1pbHlfbmFtZSI6InN0cmluZyIsImp0aSI6ImRlNDBlOTIxLTk4M2QtNGUwOC1hZTdkLWYwNDM3YjYzM2ViZCIsImV4cCI6MTcyMjI1MTg1OCwiaXNzIjoiUG9ydGFsIiwiYXVkIjoiUG9ydGFsIn0.Ii04T2mMdwbe1kE9EAhx_GjPl7D2Fd6YgDF3_uon7GI
