GET https://localhost:7181/api/Employees/GetVacations
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxZDMyZTFhZS0wMTZiLTQxZDAtYmEwYy1lNjc4M2FhZTdmZGYiLCJuYW1lIjoiQWhtZWQiLCJmYW1pbHlfbmFtZSI6IlNvbGltYW4iLCJqdGkiOiJlYThjYzEwMS0yMzE3LTQyYjMtOTdlMC1hYzRkZmZjMzVmMjQiLCJleHAiOjE3MjYwODA4NTAsImlzcyI6IlBvcnRhbCIsImF1ZCI6IlBvcnRhbCJ9.3Bes8BL7vcnB4ovhNdkSltdH2G6hAfH2s4l5VxZbMV8


{
  "employeeId": "751DEB4B-BF52-4908-BE5D-28E203DC1D36"
}