GET https://localhost:7181/api/Employees/GetVacations
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkZDdiZDdhMy0yZWE1LTRkZWYtOWMwNS1mZmIwYzdlZGJiYjUiLCJuYW1lIjoiU2F5ZWQiLCJmYW1pbHlfbmFtZSI6IlNvbGltYW4iLCJqdGkiOiJmN2QzNGViMC02NmIzLTQ1ODgtYmEzMS01YzkwZjJhMTUyNGMiLCJleHAiOjE3MjUzNTc2NjAsImlzcyI6IlBvcnRhbCIsImF1ZCI6IlBvcnRhbCJ9.-cTNGHdfGlIsmQh1p9bdATV3SBN6kNXO4uJsNwl5X5c
 

{
  "employeeId": "DD7BD7A3-2EA5-4DEF-9C05-FFB0C7EDBBB5"
}