Get https://localhost:7181/api/Manager/GetEmployeesVacations
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxZDMyZTFhZS0wMTZiLTQxZDAtYmEwYy1lNjc4M2FhZTdmZGYiLCJuYW1lIjoiQWhtZWQiLCJmYW1pbHlfbmFtZSI6IlNvbGltYW4iLCJqdGkiOiI2MTFjYWFkMC01ZTQyLTQwZjQtOTQ2MC00NjM5MzNjZTNmMjciLCJleHAiOjE3MjYwODcxOTIsImlzcyI6IlBvcnRhbCIsImF1ZCI6IlBvcnRhbCJ9.gTmYHyZlHTG0S4k400HDpjNdbW2vIx1n0Su5VzoYmgI

{

  "managerId": "98D623F3-CE45-4A61-B968-E1201518C1E0"

}