Get https://localhost:7181/api/Manager/GetEmployees
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJQb3J0YWwuRG9tYWluLlVzZXIuVmFsdWVPYmplY3RzLlVzZXJJZCIsIm5hbWUiOiJPZGF5IiwiZmFtaWx5X25hbWUiOiJTb2xpbWFuIiwianRpIjoiZjc3ZWJhMjgtMWUyYS00MjAzLWFiYjktZTFkM2MwZWY5OTExIiwiZXhwIjoxNzIzODk1OTkxLCJpc3MiOiJQb3J0YWwiLCJhdWQiOiJQb3J0YWwifQ.vIXu0wHyo2OcO5RaXae9ZNqB1YGOPpxLc9I5BKFm51E

{

  "managerId": "95d68b30-ca9e-4246-8d6d-c821c4bc651f"

}