Get https://localhost:7181/api/Manager/GetEmployees
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkZDdiZDdhMy0yZWE1LTRkZWYtOWMwNS1mZmIwYzdlZGJiYjUiLCJuYW1lIjoiU2F5ZWQiLCJmYW1pbHlfbmFtZSI6IlNvbGltYW4iLCJqdGkiOiIwZWM0ZTY1Yi1hYTkwLTRmMzgtYWY0NS0xMDNhZDU4YjIxYzUiLCJleHAiOjE3MjU3MTM0MTMsImlzcyI6IlBvcnRhbCIsImF1ZCI6IlBvcnRhbCJ9.f6pyMKLhNyKvFq9ELmAerEjbAEpSdcLY3PpGbMDg4qE

{

  "managerId": "DD7BD7A3-2EA5-4DEF-9C05-FFB0C7EDBBB5"

}