Get https://localhost:7181/api/Manager/GetEmployees
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0ZjBjZWVjNC0yOTIzLTQxMGYtODBhZC01ZmE4ZWEzZmMyNDQiLCJuYW1lIjoiV2FsYWEiLCJmYW1pbHlfbmFtZSI6IlNvbGltYW4iLCJqdGkiOiJhM2ZkOTgxZi0wMDZiLTQxMTMtOGZlYy1jMGE1MDllZmRjNjUiLCJleHAiOjE3MjU5OTkzMTUsImlzcyI6IlBvcnRhbCIsImF1ZCI6IlBvcnRhbCJ9.AkcTlkNb0Sqimm9p1i6G0lPx-Ms_KmWFsFggYKvugt0

{

  "managerId": "FCA22E6D-5DF1-46D8-9D37-31FBB6A86D77"

}