@host=https://localhost:7181

POST {{host}}/api/Auth/register
Content-Type: application/json

{
  "code":"3",
  "firstName": "Moustafa",
  "middleName": "Mahmood",
  "lastName": "Soliman",
  "arabicName": "„’ÿ›Ì „Õ„Êœ ”·Ì„«‰",
  "nationality": "Egyptian",
  "nationalId": 22446673155432441,
  "gender": "Male",
  "dateOfBirth": "2024-08-03T19:58:53.382Z",
  "contactNumber": "0100000",
  "address": {
    "street": "ansary",
    "city": "cairo",
    "state": "cairo",
    "postalCode": "27511",
    "country": "Egypt"
  },
  "userType": "Employee",
  "role": "NormalUser",
  "email": "moustafa@str.com",
  "password": "string"
}