@host=https://localhost:7181

POST {{host}}/api/Auth/register
Content-Type: application/json

{
  "code":"3",
  "firstName": "Oday",
  "middleName": "Abdu",
  "lastName": "Soliman",
  "arabicName": "⁄œÌ ⁄»œ«·—Õ„‰ ”·Ì„«‰",
  "nationality": "Egyptian",
  "nationalId": 224496123135354321,
  "gender": "Male",
  "dateOfBirth": "2024-08-03T19:58:53.382Z",
  "contactNumber": "0100000",
  "address": {
    "street": "ansary",
    "city": "cairo",
    "state": "cairo",
    "postalCode": "27511",
    "country": "Egypt"
  },
  "userType": "Employee",
  "role": "NormalUser",
  "email": "oday@str.com",
  "password": "string"
}