POST https://localhost:7181/api/Admin/SetEmployeeAsManager
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJQb3J0YWwuRG9tYWluLlVzZXIuVmFsdWVPYmplY3RzLlVzZXJJZCIsIm5hbWUiOiJPZGF5IiwiZmFtaWx5X25hbWUiOiJTb2xpbWFuIiwianRpIjoiYTFmNzAyZmEtM2NjNy00YWFiLTg4M2YtNDUwOGZkNzI3YjY1IiwiZXhwIjoxNzIzNzI2NTQ0LCJpc3MiOiJQb3J0YWwiLCJhdWQiOiJQb3J0YWwifQ.pqn-3UW3OadRPggnB3aXjjbnElq3KvGMOjLuiDq4EdM

{

    "adminId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
    "employeeId": "29ee1ee4-ddb0-4f59-a122-7c4073289d18"

}