POST https://localhost:7181/api/Employees/applyVacation
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJQb3J0YWwuRG9tYWluLlVzZXIuVmFsdWVPYmplY3RzLlVzZXJJZCIsIm5hbWUiOiJPZGF5IiwiZmFtaWx5X25hbWUiOiJTb2xpbWFuIiwianRpIjoiZGIyM2RiMTktNDkxNy00ZTY2LWEzNjktZWZhYzgzYWU3NDJkIiwiZXhwIjoxNzIzODIyOTM5LCJpc3MiOiJQb3J0YWwiLCJhdWQiOiJQb3J0YWwifQ.7JRDCVj_w1zZ0deEXZk_TZsO-sdLEWJ4OrHJgE0oYM8

{
  "employeeId": "362d111b-f1e9-4d99-a55a-40c16f0f143a",
  "startFrom": "2024-08-05T22:23:13.534Z",
  "endAt": "2024-08-06T22:23:13.534Z",
  "vacationType": "≈⁄ Ì«œÌ"
}