POST https://localhost:7181/api/Employees/applyVacation
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJQb3J0YWwuRG9tYWluLlVzZXIuVmFsdWVPYmplY3RzLlVzZXJJZCIsIm5hbWUiOiJPZGF5IiwiZmFtaWx5X25hbWUiOiJTb2xpbWFuIiwianRpIjoiYTFmNzAyZmEtM2NjNy00YWFiLTg4M2YtNDUwOGZkNzI3YjY1IiwiZXhwIjoxNzIzNzI2NTQ0LCJpc3MiOiJQb3J0YWwiLCJhdWQiOiJQb3J0YWwifQ.pqn-3UW3OadRPggnB3aXjjbnElq3KvGMOjLuiDq4EdM

{
  "employeeId": "29ee1ee4-ddb0-4f59-a122-7c4073289d18",
  "startFrom": "2024-08-05T22:23:13.534Z",
  "endAt": "2024-08-06T22:23:13.534Z",
  "vacationType": "≈⁄ Ì«œÌ"
}